### PR TITLE
Separate apps

### LINKED ISSUE #55: Separate Safe apps
Currently all Safe apps are 1 React app. This cause issues when updating dependencies and also with meta information files. Therefore we should properly separate them so that each safe app is their own react app (they can still all exist in the same repo).

### PR DESCRIPTION
**Pull request by nicosampler**
closes #55 #56.  
Now, each safe-app is an independent app.

- I have used `yarn workspaces` to unify dependencies.
- In the main `package.json` there are scripts to start and build each app independently.
- I have used `dotenv-cli` to only have one .env shared for all the apps. 
- I changed the logic to form the URL provider, for xdai, volta, and EWC, the URL is harcoded, for rinkeby and mainnet it uses the env var REACT_APP_RPC_TOKEN to form the URL. This will be handy to make work the same build in all networks.

### CODE REVIEW

**Review by rmeissner — APPROVED** [review]
As far as I can tell it looks good ... if I have a chance I will try all the projects locally, but won't be able to this week :/

**Comment by mikheevm** [comment]
wdyt about including apps in a single folder?
```
packages/apps
  - compound
  - walletconnect
  - ...
```

this way we won't have to add a new entry to `package.json` when adding a new app

also, I'm not sure about scripts to run the apps, usually with workspaces it looks like that `yarn workspace compound run start`

**Comment by mikheevm** [comment]
Also please update readme :)

**Comment by nicosampler** [comment]
> wdyt about including apps in a single folder?
> 
> ```
> packages (or apps)
>   - compound
>   - walletconnect
>   - ...
> ```
> 
> this way we won't have to add a new entry to `package.json` when adding a new app

As far I understand it will not work with yarn workspaces.

> 
> also, I'm not sure about scripts to run the apps, usually with workspaces it looks like that `yarn workspace compound run start`

It's great, didn't know about it.

**Comment by mikheevm** [comment]
> As far I understand it will not work with yarn workspaces.

It will.

```
  "workspaces": {
    "packages": [
      "packages/*"
    ]
  },
```

**Comment by mikheevm** [comment]
We also can remove tsconfig.json from each app and use a single file, an example of such tsconfig:
```
  
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "strictNullChecks": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": false,
    "jsx": "react"
  },
  "include": ["./apps/*/**/src"],
  "exclude": ["dist", "node_modules"]
}
```

**Comment by nicosampler** [comment]
@mikheevm I tested the single tsconfig.json for all the apps, but it's not working, typescript automatically creates a `tsconfig` on each app when you start the app, and the first time you run it without the tsconfig it fails, if you re-run the app, now with the tsconfig created automatically, it works fine. 

I have been looking at other projects and all of them have a file for each workspace.

**Review by dasanra — COMMENTED** [review]
As we talked. It would be nice to remove Storybook dependencies as they aren't in use

**Comment by nicosampler** [comment]
@dasanra I just pushed a commit that removed storybook.

**Review by dasanra — APPROVED** [review]

**Comment by dasanra** [comment]
@nicosampler I scheduled a meeting with devops to comment on how to handle automatic build and deployment process. Until then we can handle them as external apps

**Comment by dasanra** [comment]
Added a comment in the issue on why we are marking this as resolved. Only CI is pending

https://github.com/gnosis/safe-react-apps/issues/55#issuecomment-726112149

**Pull request merged**
