### PR TITLE
[WC] Upgrade the client to the latest version

### PR DESCRIPTION
**Pull request by katspaugh**
WalletConnect is asking dapps to update their integration: https://twitter.com/WalletConnect/status/1422169112751529989

Screenshot 2021-08-04 at 10 46 21

It looks like they are working on v2 (there's a beta published on NPM). Maybe that would be even better but for now, let's just upgrade to the latest package.

### CODE REVIEW

**Review by mikheevm — APPROVED** [review]
good catch!

**Comment by katspaugh** [comment]
FWIW, I've tested it on mainnet with SushiSwap. Seems to work a bit better than before (confirmation popup appearing faster).

**Comment by odd-amphora** [comment]
Any idea when this will be merged?

**Comment by francovenica** [comment]
I was able to use the App in rinkeby and mainnet:
Tx 1163 in this safe https://rinkeby.gnosis-safe.io/app/#/safes/0x9913B9180C20C6b0F21B6480c84422F6ebc4B808/transactions
and Tx 201 in this safe https://gnosis-safe.io/app/#/safes/0x8675B754342754A30A2AeF474D114d8460bca19b/transactions

Looks good to me

**Pull request merged**
