### PR TITLE
chore: configure prettier

### PR DESCRIPTION
**Pull request by dasanra**
## What it solves
We are not using Prettier to follow code style guidelines. Also the rules were not quite aligned with other repositories. We will try to align all repositories to use same code styling rules.

## How this PR fixes it
- Update prettier configuration file
- Add a task to use prettier before each commit on staged files
- Configure eslint to avoid rules issues
- Lint all current code

### CODE REVIEW

**Review by yagopv — APPROVED** [review]

**Comment by mikheevm** [comment]
Why do we remove print width? Imo the default 80 is too small

**Comment by mikheevm** [comment]
https://github.com/safe-global/safe-react/blob/dev/.prettierrc safe-react is still using 120

**Comment by yagopv** [comment]
Not sure but I like the 80 option 😬. For me is more readable

**Comment by dasanra** [comment]
> https://github.com/safe-global/safe-react/blob/dev/.prettierrc safe-react is still using 120

@mikheevm yes it was a push to something more readable, I wanted to experiment with the apps first before proposing this cutdown also in `safe-react`

For me as I usually work with lots of windows side to side it's much more convenient to avoid horizontal scroll. Also 80 is the old standard for programming :smile:

**Comment by mikheevm** [comment]
What screens you all have?

**Comment by yagopv** [comment]
haha, currently ultrawide indeed 😂

**Comment by dasanra** [comment]
> What screens you all have? joy if you open a file with 500+ lines with 80 line rule, you get a minimal code vertically...

After discused internally we decided on testing with 100 chars length lines

**Pull request merged**
